version: "3.1"

services:
  secret-server:
    build: ./backend
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  secret-frontend:
    build: ./frontend-vue
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
